server {
    listen 80;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://fearless-purpose-production-9754.up.railway.app;
        proxy_ssl_server_name on;
        proxy_set_header Host fearless-purpose-production-9754.up.railway.app;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 30s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /ngsw.json {
        expires -1;
    }

    location = /index.html {
        expires -1;
    }
}
